# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-05 18:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=256)),
                ('cellphone', models.IntegerField()),
                ('landphone', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('breed', models.CharField(blank=True, max_length=256, null=True)),
                ('hair_type', models.CharField(blank=True, choices=[('short', 'Corto'), ('medium', 'Medio'), ('long', 'Largo')], max_length=100, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('annotations', models.CharField(blank=True, max_length=2048, null=True)),
                ('owners', models.ManyToManyField(to='happy.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='PetPictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1024)),
                ('description', models.CharField(max_length=2048)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='happy.Pet')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('cost', models.FloatField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='happy.Pet'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='services',
            field=models.ManyToManyField(to='happy.Service'),
        ),
    ]
