# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-06 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='datetime',
            new_name='end',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='duration',
        ),
        migrations.AddField(
            model_name='appointment',
            name='start',
            field=models.DateTimeField(default='2016-01-22'),
            preserve_default=False,
        ),
    ]
