# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-06 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happy', '0002_auto_20160306_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='notes',
            field=models.CharField(default='', max_length=2048),
            preserve_default=False,
        ),
    ]
