# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-12 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happy', '0003_appointment_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
