# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happy', '0004_pet_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='club_happy',
            field=models.BooleanField(default=False),
        ),
    ]
