# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-03 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happy', '0005_customer_club_happy'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='birthday_week',
            field=models.IntegerField(null=True),
        ),
    ]
