# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-03 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happy', '0007_auto_20160403_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='amount_paid',
            field=models.FloatField(default=0),
        ),
    ]
