# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-10 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happy', '0009_auto_20160410_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cellphone',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='landphone',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
