# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-16 23:01
from __future__ import unicode_literals

from django.db import migrations, models
import happy.models


class Migration(migrations.Migration):

    dependencies = [
        ('happy', '0010_auto_20160410_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petpictures',
            name='url',
        ),
        migrations.AddField(
            model_name='pet',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=happy.models.get_upload_path),
        ),
        migrations.AddField(
            model_name='petpictures',
            name='picture',
            field=models.ImageField(default='', upload_to=happy.models.get_upload_path),
            preserve_default=False,
        ),
    ]
