# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-24 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happy', '0013_auto_20160424_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petbreed',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
