# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-24 15:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('happy', '0014_auto_20160424_1451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='weight',
            new_name='size',
        ),
    ]
